[project]
name = 'Tokenized-Agricultural-Cooperative-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.collective-purchasing]
path = 'contracts/collective-purchasing.clar'
clarity_version = 2
epoch = 2.5

[contracts.member-verification]
path = 'contracts/member-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
